public enum EventID
{
  
    NONE,
    PLAYER_DEAD = 1,
    PLAYER_RESPAWN = 2,
    DISABLE_OUTLINE_BIRD = 3,
    BUY_PRODUCT_SUCCESS_FIRST = 4,
    BUY_PRODUCT_SUCCESS = 5,
    CHANGE_LANGUAGE = 6,
    REMOVE_ADS = 7,
    FLY_OUT_RANDOM = 8,
    MINI_GAME_CONNECT_BIRD_EGG = 9,

    ScrollEndChange = 100,
    CHANGE_COIN = 101,
    CHANGE_STAR = 102,

    GAME_COMPLETED = 200,
    HEART_UPDATE = 201,
    BOOSTER_COUNT_CHANGED = 202,

    CHANGE_GEM = 301,
    LEVEL_PROGRESS_CHANGE = 302,
}
